name = "newsnow"
main = "dist/output/server/index.mjs"
compatibility_date = "2024-03-03"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "newsnow-db"
database_id = "6c6f3003-d118-4ac2-b090-2cf4f48f6ac9"

[vars]
INIT_TABLE = "true"
